<?php

declare(strict_types=1);

use App\Application\Actions\ProcessProductBatchAction;
use App\Domain\Marketplace\ProductData;
use App\Domain\Pricing\Money;
use App\Models\Marketplace;
use App\Models\PriceHistory;
use App\Models\Product;
use Illuminate\Support\Facades\DB;

beforeEach(function () {
    $this->marketplace = Marketplace::factory()->create(['slug' => 'upsert-test']);
    $this->action = app(ProcessProductBatchAction::class);
});

function productData(string $externalId, string $price, ?string $previous = null, array $overrides = []): ProductData
{
    return new ProductData(
        externalId: $externalId,
        title: $overrides['title'] ?? "Produto {$externalId}",
        productUrl: "https://shop.test/p/{$externalId}",
        currentPrice: Money::fromNumericString($price),
        previousPrice: $previous === null ? null : Money::fromNumericString($previous),
        listPrice: $overrides['listPrice'] ?? null,
        // array_key_exists, not ??, so a test can deliberately pass null.
        brand: array_key_exists('brand', $overrides) ? $overrides['brand'] : 'Marca',
        rating: $overrides['rating'] ?? 4.5,
        reviewsCount: $overrides['reviewsCount'] ?? 100,
        inStock: $overrides['inStock'] ?? true,
        rawPayload: ['source' => 'test'],
    );
}

it('inserts new products in one batch', function () {
    $result = $this->action->execute($this->marketplace, [
        productData('A1', '100.00'),
        productData('A2', '200.00'),
        productData('A3', '300.00'),
    ]);

    expect($result->productsUpserted)->toBe(3)
        ->and(Product::count())->toBe(3);
});

it('updates rather than duplicates on the next capture', function () {
    $this->action->execute($this->marketplace, [productData('A1', '100.00')]);
    $this->action->execute($this->marketplace, [productData('A1', '80.00')]);

    // The natural key is (marketplace_id, external_id); a second capture of the
    // same item must never create a second row.
    expect(Product::count())->toBe(1)
        ->and(Product::first()?->current_price?->toNumericString())->toBe('80.00');
});

it('carries the last observed price into previous_price when it changes', function () {
    $this->action->execute($this->marketplace, [productData('A1', '100.00')]);
    $this->action->execute($this->marketplace, [productData('A1', '75.00')]);

    $product = Product::first();

    expect($product?->previous_price?->toNumericString())->toBe('100.00')
        // Generated by the database from the two prices.
        ->and($product?->discount_percent)->toBe(25);
});

it('leaves previous_price alone when the price has not moved', function () {
    $this->action->execute($this->marketplace, [productData('A1', '100.00')]);
    $this->action->execute($this->marketplace, [productData('A1', '75.00')]);
    $this->action->execute($this->marketplace, [productData('A1', '75.00')]);

    // A repeated identical reading must not collapse the discount to zero by
    // making the previous price equal to the current one.
    expect(Product::first()?->previous_price?->toNumericString())->toBe('100.00');
});

it('tracks the all time low and high without reading first', function () {
    foreach (['100.00', '60.00', '140.00', '90.00'] as $price) {
        $this->action->execute($this->marketplace, [productData('A1', $price)]);
    }

    $product = Product::first();

    expect($product?->lowest_price_ever?->toNumericString())->toBe('60.00')
        ->and($product?->highest_price_ever?->toNumericString())->toBe('140.00');
});

it('keeps the richer value when a later capture omits a field', function () {
    $this->action->execute($this->marketplace, [productData('A1', '100.00', overrides: ['brand' => 'Mondial'])]);
    $this->action->execute($this->marketplace, [productData('A1', '100.00', overrides: ['brand' => null])]);

    // A marketplace that intermittently omits the brand should not erase it.
    expect(Product::first()?->brand)->toBe('Mondial');
});

it('never lets the review count go backwards', function () {
    $this->action->execute($this->marketplace, [productData('A1', '100.00', overrides: ['reviewsCount' => 500])]);
    $this->action->execute($this->marketplace, [productData('A1', '100.00', overrides: ['reviewsCount' => 12])]);

    expect(Product::first()?->reviews_count)->toBe(500);
});

it('stores the normalised title for cross marketplace matching', function () {
    $this->action->execute($this->marketplace, [
        productData('A1', '100.00', overrides: ['title' => 'Cafeteira Elétrica, Inox 220V!']),
    ]);

    expect(Product::first()?->normalized_title)->toBe('cafeteira eletrica inox 220v');
});

it('gives each product a stable identity hash', function () {
    $this->action->execute($this->marketplace, [productData('A1', '100.00')]);
    $before = DB::scalar('SELECT encode(identity_hash, ?) FROM products', ['hex']);

    $this->action->execute($this->marketplace, [productData('A1', '55.00')]);
    $after = DB::scalar('SELECT encode(identity_hash, ?) FROM products', ['hex']);

    expect($after)->toBe($before);
});

it('revives a soft deleted product when the marketplace lists it again', function () {
    $this->action->execute($this->marketplace, [productData('A1', '100.00')]);
    Product::first()?->delete();

    $this->action->execute($this->marketplace, [productData('A1', '90.00')]);

    expect(Product::withTrashed()->count())->toBe(1)
        ->and(Product::count())->toBe(1);
});

it('handles a batch of one hundred in a single statement', function () {
    $products = [];
    for ($index = 1; $index <= 100; $index++) {
        $products[] = productData("BULK-{$index}", '10.00');
    }

    DB::enableQueryLog();
    $this->action->execute($this->marketplace, $products);
    $queries = DB::getQueryLog();
    DB::disableQueryLog();

    expect(Product::count())->toBe(100)
        // One upsert plus one history insert. A round trip per product would be a
        // hundred times the latency for the same work.
        ->and(collect($queries)->filter(fn (array $q): bool => str_contains($q['query'], 'insert into products')
            || str_contains($q['query'], 'INSERT INTO products')))->toHaveCount(1);
});

it('records a price observation for every new product', function () {
    $result = $this->action->execute($this->marketplace, [
        productData('A1', '100.00'),
        productData('A2', '200.00'),
    ]);

    expect($result->observationsRecorded)->toBe(2)
        ->and(PriceHistory::count())->toBe(2);
});
