<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE products (
                id                  bigserial PRIMARY KEY,
                public_id           uuid NOT NULL DEFAULT gen_random_uuid(),
                marketplace_id      bigint NOT NULL REFERENCES marketplaces(id) ON DELETE CASCADE,
                external_id         text NOT NULL,
                identity_hash       bytea NOT NULL,
                title               text NOT NULL,
                normalized_title    text NOT NULL,
                brand               text,
                category_id         bigint REFERENCES categories(id) ON DELETE SET NULL,
                image_url           text,
                product_url         text NOT NULL,
                affiliate_url       text,
                rating              numeric(2,1),
                reviews_count       integer NOT NULL DEFAULT 0,
                is_prime            boolean NOT NULL DEFAULT false,
                has_free_shipping   boolean NOT NULL DEFAULT false,
                in_stock            boolean NOT NULL DEFAULT true,
                current_price       money_brl,
                previous_price      money_brl,
                lowest_price_ever   money_brl,
                highest_price_ever  money_brl,

                -- Generated by the database so the stored discount can never
                -- disagree with the stored prices, which is a whole class of bug
                -- the application simply cannot commit.
                discount_percent    smallint GENERATED ALWAYS AS (
                    CASE WHEN previous_price IS NULL OR previous_price = 0 THEN 0
                         ELSE floor(((previous_price - current_price) / previous_price) * 100)::smallint
                    END
                ) STORED,

                -- Also generated, which is why product_search_vector had to be
                -- declared IMMUTABLE in the first migration.
                search_vector       tsvector GENERATED ALWAYS AS (
                    product_search_vector(title, brand, null)
                ) STORED,

                raw_payload         jsonb NOT NULL DEFAULT '{}'::jsonb,
                first_seen_at       timestamptz NOT NULL DEFAULT now(),
                last_seen_at        timestamptz NOT NULL DEFAULT now(),
                created_at          timestamptz NOT NULL DEFAULT now(),
                updated_at          timestamptz NOT NULL DEFAULT now(),
                deleted_at          timestamptz,
                CONSTRAINT uq_products_marketplace_external UNIQUE (marketplace_id, external_id),
                CONSTRAINT uq_products_identity_hash UNIQUE (identity_hash),
                CONSTRAINT uq_products_public_id UNIQUE (public_id),
                CONSTRAINT chk_products_rating
                    CHECK (rating IS NULL OR rating BETWEEN 0 AND 5),
                CONSTRAINT chk_products_reviews_count CHECK (reviews_count >= 0)
            );

            COMMENT ON COLUMN products.identity_hash IS
                'digest() over the normalised marketplace + external id (+ variation). bytea rather than hex text halves the index size.';
            COMMENT ON COLUMN products.normalized_title IS
                'Lowercased, unaccented, unpunctuated title. Used for cross-marketplace equivalence via trigram similarity.';

            -- Full text search over the weighted document.
            CREATE INDEX idx_products_search_vector ON products USING gin (search_vector);

            -- Trigram similarity, used both as the fallback when full text search
            -- returns nothing and to detect the same product across marketplaces.
            CREATE INDEX idx_products_normalized_title_trgm
                ON products USING gin (normalized_title gin_trgm_ops);

            -- jsonb_path_ops indexes only containment, producing a smaller and
            -- faster index than the default jsonb_ops. Queries against the raw
            -- payload are always "does it contain this".
            CREATE INDEX idx_products_raw_payload
                ON products USING gin (raw_payload jsonb_path_ops);

            CREATE INDEX idx_products_marketplace_last_seen
                ON products (marketplace_id, last_seen_at DESC);

            -- Serves the "best current deals in a category" listing. Partial, so
            -- soft deleted and out of stock rows are not indexed at all.
            CREATE INDEX idx_products_category_discount
                ON products (category_id, discount_percent DESC)
                WHERE deleted_at IS NULL AND in_stock;
        SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE IF EXISTS products CASCADE;');
    }
};
